<a href="https://colab.research.google.com/github/asmipandey18/Machine_learning/blob/main/Data_cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv("/content/my_file (1).csv")

In [ ]:
df.head(10)

,Rank,Peak,All Time Peak,Actual gross,Adjusted gross (in 2022 dollars),Artist,Tour title,Year(s),Shows,Average gross,Ref.
0,1,1,2,"$780,000,000","$780,000,000",Taylor Swift,The Eras Tour †,2023–2024,56,"$13,928,571",[1]
1,2,1,7[2],"$579,800,000","$579,800,000",Beyoncé,Renaissance World Tour,2023,56,"$10,353,571",[3]
2,3,1[4],2[5],"$411,000,000","$560,622,615",Madonna,Sticky & Sweet Tour ‡[4][a],2008–2009,85,"$4,835,294",[6]
3,4,2[7],10[7],"$397,300,000","$454,751,555",Pink,Beautiful Trauma World Tour,2018–2019,156,"$2,546,795",[7]
4,5,2[4],NaN,"$345,675,146","$402,844,849",Taylor Swift,Reputation Stadium Tour,2018,53,"$6,522,173",[8]
5,6,2[4],10[9],"$305,158,363","$388,978,496",Madonna,The MDNA Tour,2012,88,"$3,467,709",[9]
6,7,2[10],NaN,"$280,000,000","$381,932,682",Celine Dion,Taking Chances World Tour,2008–2009,131,"$2,137,405",[11]
7,7,NaN,NaN,"$257,600,000","$257,600,000",Pink,Summer Carnival †,2023–2024,41,"$6,282,927",[12]
8,9,NaN,NaN,"$256,084,556","$312,258,401",Beyoncé,The Formation World Tour,2016,49,"$5,226,215",[13]
9,10,NaN,NaN,"$250,400,000","$309,141,878",Taylor Swift,The 1989 World Tour,2015,85,"$2,945,882",[14]

In [ ]:
df.shape

(20, 11)

In [ ]:
df.columns

Index(['Rank', 'Peak', 'All Time Peak', 'Actual gross',
       'Adjusted gross (in 2022 dollars)', 'Artist', 'Tour title', 'Year(s)',
       'Shows', 'Average gross', 'Ref.'],
      dtype='object')

In [ ]:
df.dtypes

Rank                                 int64
Peak                                object
All Time Peak                       object
Actual gross                        object
Adjusted gross (in 2022 dollars)    object
Artist                              object
Tour title                          object
Year(s)                             object
Shows                                int64
Average gross                       object
Ref.                                object
dtype: object

In [ ]:
df.isnull().sum()

rank                              0
peak                             11
all_time_peak                    14
actualgross                       0
adjustedgross_in_2022_dollars     0
artist                            0
tour_title                        0
years                             0
shows                             0
average_gross                     0
ref                               0
dtype: int64

In [ ]:
df["peak"] = df["peak"].fillna("delete_me")

In [ ]:
df["all_time_peak"] = df["all_time_peak"].fillna("do_not_delete_me")

In [ ]:
df.isnull().sum()

rank                             0
peak                             0
all_time_peak                    0
actualgross                      0
adjustedgross_in_2022_dollars    0
artist                           0
tour_title                       0
years                            0
shows                            0
average_gross                    0
ref                              0
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.columns = df.columns.str.lower()
df.columns = df.columns.str.strip()
df.columns = df.columns.str.replace(" ", "_")
df.columns = df.columns.str.replace(r"[^a-zA-Z0-9_]", "", regex=True)
print(df.columns)

Index(['rank', 'peak', 'all_time_peak', 'actualgross',
       'adjustedgross_in_2022_dollars', 'artist', 'tour_title', 'years',
       'shows', 'average_gross', 'ref'],
      dtype='object')

In [ ]:
df.rename(columns={
    "actualgross": "actual_gross",
    "adjustedgross_in_2022_dollars": "adjusted_gross_in_2022_dollars"
}, inplace=True)

In [ ]:
print(df.columns)

Index(['rank', 'peak', 'all_time_peak', 'actual_gross',
       'adjusted_gross_in_2022_dollars', 'artist', 'tour_title', 'years',
       'shows', 'average_gross', 'ref'],
      dtype='object')

In [ ]:
df["peak"] = df["peak"].str.replace(r"\[.*?\]", "", regex=True)

In [ ]:
print(df["peak"])

0             1
1             1
2             1
3             2
4             2
5             2
6             2
7     delete_me
8     delete_me
9     delete_me
10    delete_me
11    delete_me
12    delete_me
13            1
14            2
15    delete_me
16    delete_me
17    delete_me
18    delete_me
19    delete_me
Name: peak, dtype: object

In [ ]:
df["all_time_peak"] = df["all_time_peak"].str.replace(
    r"\[.*?\]", "", regex=True
)

In [ ]:
print(df["all_time_peak"])

0                    2
1                    7
2                    2
3                   10
4     do_not_delete_me
5                   10
6     do_not_delete_me
7     do_not_delete_me
8     do_not_delete_me
9     do_not_delete_me
10    do_not_delete_me
11                  14
12    do_not_delete_me
13    do_not_delete_me
14    do_not_delete_me
15    do_not_delete_me
16    do_not_delete_me
17    do_not_delete_me
18    do_not_delete_me
19    do_not_delete_me
Name: all_time_peak, dtype: object

In [ ]:
df["actual_gross"] = df["actual_gross"].str.replace(r"\[.*?\]", "", regex=True)

df["actual_gross"] = df["actual_gross"].str.replace("$", "", regex=False)
df["actual_gross"] = df["actual_gross"].str.replace(",", "", regex=False)

df["actual_gross"] = pd.to_numeric(df["actual_gross"])

In [ ]:
print(df["actual_gross"].head())
print(df["actual_gross"].dtype)

0    780000000
1    579800000
2    411000000
3    397300000
4    345675146
Name: actual_gross, dtype: int64
int64

In [ ]:
df["adjusted_gross_in_2022_dollars"] = df["adjusted_gross_in_2022_dollars"].str.replace("$", "", regex=False)

df["adjusted_gross_in_2022_dollars"] = df["adjusted_gross_in_2022_dollars"].str.replace(",", "", regex=False)

df["adjusted_gross_in_2022_dollars"] = pd.to_numeric(
    df["adjusted_gross_in_2022_dollars"]
)

In [ ]:
df["adjusted_gross_in_2022_dollars"].head()

0    780000000
1    579800000
2    560622615
3    454751555
4    402844849
Name: adjusted_gross_in_2022_dollars, dtype: int64

In [ ]:
df["adjusted_gross_in_2022_dollars"].dtype

dtype('int64')

In [ ]:
df["tour_title"] = df["tour_title"].str.replace(
    r"[^a-zA-Z0-9\s]", "", regex=True
)

In [ ]:
df["tour_title"].head()

0                 The Eras Tour
1         Renaissance World Tour
2          Sticky  Sweet Tour 4a
3    Beautiful Trauma World Tour
4        Reputation Stadium Tour
Name: tour_title, dtype: object

In [ ]:
def clean_year(x):
    x = str(x).replace("–", "-")

    if "-" in x:
        start, end = x.split("-", 1)

        if len(end) == 2:
            end = start[:2] + end

        return f"{start}, {end}"

    return x

df["years"] = df["years"].apply(clean_year)

In [47]:
df["years"].head()

0    2023, 2024
1          2023
2    2008, 2009
3    2018, 2019
4          2018
Name: years, dtype: object

In [48]:
df["average_gross"] = df["average_gross"].str.replace("$", "", regex=False)

df["average_gross"] = df["average_gross"].str.replace(",", "", regex=False)

df["average_gross"] = pd.to_numeric(df["average_gross"])

In [49]:
print(df["average_gross"].to_string(index=False))

13928571
10353571
 4835294
 2546795
 6522173
 3467709
 2137405
 6282927
 5226215
 2945882
 1735606
 1118227
 1350993
  615385
 3233333
 1295775
 1734694
 2070732
 1385950
 1744186

In [50]:
print(df["average_gross"].dtype)

int64

In [51]:
df.drop("ref", axis=1, inplace=True)

In [52]:
print(df.columns)

Index(['rank', 'peak', 'all_time_peak', 'actual_gross',
       'adjusted_gross_in_2022_dollars', 'artist', 'tour_title', 'years',
       'shows', 'average_gross'],
      dtype='object')

In [53]:
print(df.info())
print(df.isnull().sum())
print("Duplicate rows:", df.duplicated().sum())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 10 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   rank                            20 non-null     int64
 1   peak                            20 non-null     object
 2   all_time_peak                   20 non-null     object
 3   actual_gross                    20 non-null     int64
 4   adjusted_gross_in_2022_dollars  20 non-null     int64
 5   artist                          20 non-null     object
 6   tour_title                      20 non-null     object
 7   years                           20 non-null     object
 8   shows                           20 non-null     int64
 9   average_gross                   20 non-null     int64
dtypes: int64(5), object(5)
memory usage: 1.7+ KB
None
rank                              0
peak                              0
all_time_peak                     0
actual_gross                      0
adjusted_gross_in_2022_dollars    0
artist                            0
tour_title                        0
years                             0
shows                             0
average_gross                     0
dtype: int64
Duplicate rows: 0